#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

cat 0/b.org > 0/b

runApplication blockMesh

#runApplication checkMesh
echo "Running setSet"
setSet -batch prechamber.setSet > log.setSet

echo "Running subsetMesh"
subsetMesh newWall -patch wand -overwrite > log.subsetMesh

# mesh refinement
#echo "Running topoSet"
#topoSet > log.topoSet

#echo "Running refineMesh"
#refineMesh -overwrite > log.refineMesh

echo "Running checkMesh"
runApplication checkMesh > log.checkMesh

runApplication setFields

runApplication $application

paraFoam -touch
